name: mypy
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install --only dev

      - name: Install pg-stage
        run: python3 setup.py install --user

      - name: Run mypy
        run: poetry run mypy .
